cluster:
  mkdir -p results/slurmOut/ &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --output=results/slurmOut/%j.out
    --account=rc_dmckay1_pi
    --time={resources.time}
    --parsable
default-resources:
  - partition=general
  - mem_mb=8000
  - time="00:30:00"
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-envmodules: True
cluster-status: status-sacct.sh
